//! The Postgres boundary.
//!
//! Everything crossing out of this module is a rendered `String`. No
//! `postgres::Row`, no `Type`, no OIDs — the UI layer never learns which engine
//! it is talking to, which is the one concession made toward a second driver
//! later (see the spec, §4.1).
//!
//! **Results come back via the simple query protocol**, which returns every
//! value already formatted as text by the server. That removes the whole
//! per-type decoding layer a generic SQL client would otherwise need: numerics
//! keep their exact precision, `jsonb` arrives as JSON, geometry arrives as the
//! hex WKB the server would print, and unknown or extension types format
//! themselves correctly instead of falling through a match arm we forgot.

use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use postgres::{Client, NoTls, SimpleQueryMessage, config::Host};

const RELATIONS_SQL: &str = "
SELECT
    namespace.nspname AS schema_name,
    class.relname AS relation_name,
    CASE class.relkind
        WHEN 'r' THEN 'table'
        WHEN 'p' THEN 'partitioned_table'
        WHEN 'v' THEN 'view'
        WHEN 'm' THEN 'materialized_view'
        WHEN 'f' THEN 'foreign_table'
    END AS relation_kind
FROM pg_catalog.pg_class AS class
JOIN pg_catalog.pg_namespace AS namespace
    ON namespace.oid = class.relnamespace
WHERE class.relkind IN ('r', 'p', 'v', 'm', 'f')
    AND namespace.nspname <> 'information_schema'
    AND namespace.nspname NOT LIKE 'pg\\_%' ESCAPE '\\'
ORDER BY namespace.nspname, class.relname
";

const ROUTINES_SQL: &str = "
SELECT
    namespace.nspname AS schema_name,
    procedure.proname AS routine_name,
    CASE procedure.prokind
        WHEN 'f' THEN 'function'
        WHEN 'p' THEN 'procedure'
    END AS routine_kind,
    pg_catalog.pg_get_function_identity_arguments(procedure.oid) AS identity_arguments,
    COALESCE(pg_catalog.pg_get_function_result(procedure.oid), '') AS result_type,
    language.lanname AS language,
    pg_catalog.pg_get_functiondef(procedure.oid) AS definition
-- Extension-owned routines are excluded. PostGIS alone installs some 750 of
-- them into `public`, and fetching every body at connect buries the handful of
-- routines the user actually wrote.
FROM pg_catalog.pg_proc AS procedure
JOIN pg_catalog.pg_namespace AS namespace
    ON namespace.oid = procedure.pronamespace
JOIN pg_catalog.pg_language AS language
    ON language.oid = procedure.prolang
WHERE procedure.prokind IN ('f', 'p')
    AND namespace.nspname <> 'information_schema'
    AND namespace.nspname NOT LIKE 'pg\\_%' ESCAPE '\\'
    AND NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_depend AS dependency
        WHERE dependency.objid = procedure.oid
            AND dependency.classid = 'pg_catalog.pg_proc'::regclass
            AND dependency.deptype = 'e'
    )
ORDER BY namespace.nspname, procedure.proname, identity_arguments
";

// The three structure queries name one relation, so they carry `{schema}` and
// `{relation}` placeholders substituted by `structure_sql`.
const STRUCTURE_COLUMNS_SQL: &str = "
SELECT
    attribute.attname AS column_name,
    pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) AS data_type,
    CASE WHEN attribute.attnotnull THEN 'no' ELSE 'yes' END AS nullable,
    -- An identity column has no pg_attrdef row, so reading only the default
    -- would report that the user must supply a value the server generates.
    CASE attribute.attidentity
        WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
        WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
        ELSE COALESCE(
            pg_catalog.pg_get_expr(attribute_default.adbin, attribute_default.adrelid),
            ''
        )
    END AS column_default
FROM pg_catalog.pg_attribute AS attribute
JOIN pg_catalog.pg_class AS class
    ON class.oid = attribute.attrelid
JOIN pg_catalog.pg_namespace AS namespace
    ON namespace.oid = class.relnamespace
LEFT JOIN pg_catalog.pg_attrdef AS attribute_default
    ON attribute_default.adrelid = class.oid
    AND attribute_default.adnum = attribute.attnum
WHERE namespace.nspname = {schema}
    AND class.relname = {relation}
    AND attribute.attnum > 0
    AND NOT attribute.attisdropped
ORDER BY attribute.attnum
";

const STRUCTURE_INDEXES_SQL: &str = "
SELECT
    index_class.relname AS object_name,
    pg_catalog.pg_get_indexdef(index_entry.indexrelid) AS definition
FROM pg_catalog.pg_index AS index_entry
JOIN pg_catalog.pg_class AS index_class
    ON index_class.oid = index_entry.indexrelid
JOIN pg_catalog.pg_class AS class
    ON class.oid = index_entry.indrelid
JOIN pg_catalog.pg_namespace AS namespace
    ON namespace.oid = class.relnamespace
WHERE namespace.nspname = {schema}
    AND class.relname = {relation}
ORDER BY index_class.relname
";

const STRUCTURE_CONSTRAINTS_SQL: &str = "
SELECT
    table_constraint.conname AS object_name,
    pg_catalog.pg_get_constraintdef(table_constraint.oid) AS definition
FROM pg_catalog.pg_constraint AS table_constraint
JOIN pg_catalog.pg_class AS class
    ON class.oid = table_constraint.conrelid
JOIN pg_catalog.pg_namespace AS namespace
    ON namespace.oid = class.relnamespace
WHERE namespace.nspname = {schema}
    AND class.relname = {relation}
ORDER BY table_constraint.conname
";

const CONNECT_TIMEOUT_SECONDS: u64 = 10;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConnectionConfig {
    pub host: String,
    pub port: Option<u16>,
    pub database: String,
    pub user: String,
    /// Blank is valid and must never be warned about — cloud IAM auth issues a
    /// short-lived token as the password, or none at all.
    pub password: String,
}

impl ConnectionConfig {
    pub fn from_url(url: &str) -> Result<Self, String> {
        if !url.starts_with("postgres://") && !url.starts_with("postgresql://") {
            return Err("Connection URL must start with postgres:// or postgresql://.".into());
        }

        let url_parts =
            url::Url::parse(url).map_err(|error| format!("Connection URL is invalid: {error}"))?;
        let has_explicit_port = url_parts.port().is_some()
            || url_parts
                .query_pairs()
                .any(|(key, _)| key.as_ref() == "port");
        let parsed: postgres::Config = url
            .parse()
            .map_err(|error| format!("Connection URL is invalid: {error}"))?;
        for (key, value) in url_parts.query_pairs() {
            if key.as_ref() == "sslmode" {
                reject_unsupported_sslmode(value.as_ref())?;
            }
        }
        let host = match parsed.get_hosts() {
            [Host::Tcp(host)] => host.clone(),
            [] => return Err("Connection URL does not contain a host.".into()),
            [_] => return Err("Connection URL contains a Unix socket host.".into()),
            _ => return Err("Connection URL contains more than one host.".into()),
        };
        let database = parsed
            .get_dbname()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| "Connection URL does not contain a database.".to_string())?
            .to_string();
        let user = parsed
            .get_user()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| "Connection URL does not contain a username.".to_string())?
            .to_string();
        let password = parsed
            .get_password()
            .map(|password| {
                std::str::from_utf8(password)
                    .map(str::to_string)
                    .map_err(|_| "Connection URL password is not valid UTF-8.".to_string())
            })
            .transpose()?
            .unwrap_or_default();

        Ok(Self {
            host,
            port: has_explicit_port
                .then(|| parsed.get_ports().first().copied())
                .flatten(),
            database,
            user,
            password,
        })
    }

    /// libpq key/value connection string.
    ///
    /// Values are single-quoted and escaped rather than interpolated bare, so
    /// that a username containing `@` or a password containing a space is
    /// passed through intact instead of truncating the string.
    pub fn connection_string(&self) -> String {
        let mut parts = vec![
            format!("host={}", quote(&self.host)),
            format!("dbname={}", quote(&self.database)),
            format!("user={}", quote(&self.user)),
        ];
        if let Some(port) = self.port {
            parts.push(format!("port={port}"));
        }
        if !self.password.is_empty() {
            parts.push(format!("password={}", quote(&self.password)));
        }
        // Without this the driver waits out the OS SYN retry budget, so a host
        // that resolves but drops packets pins the UI in "Connecting…" for
        // minutes with no cancel.
        parts.push(format!("connect_timeout={CONNECT_TIMEOUT_SECONDS}"));
        parts.join(" ")
    }

    pub fn endpoint(&self) -> String {
        match self.port {
            Some(port) => format!("{}:{port}", self.host),
            None => self.host.clone(),
        }
    }
}

fn quote(value: &str) -> String {
    let escaped = value.replace('\\', r"\\").replace('\'', r"\'");
    format!("'{escaped}'")
}

/// Slate connects with `NoTls`. The driver's default `sslmode` is `prefer`,
/// which silently falls back to plaintext without even sending an SSLRequest —
/// so a pasted `?sslmode=require` would put the user's credentials on the wire
/// in the clear while the UI reported success. Refuse instead, until TLS lands.
pub fn reject_unsupported_sslmode(mode: &str) -> Result<(), String> {
    match mode.trim().to_ascii_lowercase().as_str() {
        "" | "disable" | "prefer" => Ok(()),
        other => Err(format!(
            "sslmode={other} requires TLS, which Slate does not support yet."
        )),
    }
}

/// One column of a result set.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Column {
    pub name: String,
    /// The server's own name for the column's type — `int4`, `jsonb`,
    /// `timestamptz` — as a Slate-owned string, never a driver type.
    ///
    /// Absent rather than guessed. The simple query protocol carries no type
    /// information at all, so this is learned by describing the statement, and
    /// Postgres will not describe everything (see [`column_types`]).
    pub data_type: Option<String>,
}

/// A cell value, already formatted by the server. `None` is SQL NULL, which is
/// distinct from an empty string and must stay distinguishable in the grid.
pub type Cell = Option<String>;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RelationKind {
    Table,
    PartitionedTable,
    View,
    MaterializedView,
    ForeignTable,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Relation {
    pub name: String,
    pub kind: RelationKind,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RoutineKind {
    Function,
    Procedure,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Routine {
    pub name: String,
    pub kind: RoutineKind,
    pub identity_arguments: String,
    pub result_type: String,
    pub language: String,
    pub definition: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Schema {
    pub name: String,
    pub relations: Vec<Relation>,
    pub routines: Vec<Routine>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Catalog {
    pub schemas: Vec<Schema>,
}

/// One relation's definition. Loaded when the relation is opened rather than at
/// connect: a database with thousands of relations would pay for every one of
/// them to show the columns of the one that was clicked.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Structure {
    pub columns: Vec<ColumnDefinition>,
    pub indexes: Vec<NamedDefinition>,
    pub constraints: Vec<NamedDefinition>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ColumnDefinition {
    pub name: String,
    pub data_type: String,
    pub nullable: bool,
    pub default: Option<String>,
}

/// An index or a constraint, as the name plus the server's own rendering of it.
/// Postgres already prints both as readable DDL, so parsing them into fields
/// would only lose information.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NamedDefinition {
    pub name: String,
    pub definition: String,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct QueryResult {
    pub columns: Vec<Column>,
    pub rows: Vec<Vec<Cell>>,
    /// Total bytes of returned cell text. Shown in the status bar so the cost
    /// of a wide or geometry-heavy result is visible rather than mysterious.
    pub bytes: usize,
    pub elapsed: Duration,
    /// The command's server-reported row count. The simple protocol reports
    /// zero both for commands that affected no rows and commands without a row
    /// count, so callers must not infer the command kind from this value.
    pub rows_affected: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DbError {
    pub message: String,
    /// Byte offset into the submitted statement, when the server reports one.
    /// Used to point at the offending token instead of the whole statement.
    pub position: Option<usize>,
}

impl std::fmt::Display for DbError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for DbError {}

/// A live connection. Cloneable so a background task can take one without
/// borrowing the view.
///
/// ponytail: one mutex per connection, so queries on a profile serialise. A
/// profile runs one query at a time by design; revisit only if concurrent
/// statements per connection become a feature.
#[derive(Clone)]
pub struct Connection {
    client: Arc<Mutex<Client>>,
}

impl Connection {
    pub fn open(config: ConnectionConfig) -> Result<Self, DbError> {
        let client = Client::connect(&config.connection_string(), NoTls)
            .map_err(|error| connect_error(&error, &config))?;

        Ok(Self {
            client: Arc::new(Mutex::new(client)),
        })
    }

    /// Run one statement verbatim.
    ///
    /// The SQL is never rewritten — no limit injected, no reformatting. Row
    /// limits belong to the caller that *generated* a query, never to one the
    /// user typed.
    pub fn query(&self, sql: &str) -> Result<QueryResult, DbError> {
        self.run(sql, true)
    }

    /// Slate's own SQL. Its column types are never shown, so it does not pay
    /// for the extra round trip that learns them.
    fn internal_query(&self, sql: &str) -> Result<QueryResult, DbError> {
        self.run(sql, false)
    }

    fn run(&self, sql: &str, typed: bool) -> Result<QueryResult, DbError> {
        let mut client = self.client.lock().map_err(|_| DbError {
            message: "The connection is unavailable after an earlier internal failure.".into(),
            position: None,
        })?;

        let types = match typed {
            true => column_types(&mut client, sql),
            false => Vec::new(),
        };

        // Timed from here, not from the call: one client serialises a profile's
        // queries, and time spent waiting behind the catalog load is not time
        // the server spent on this statement.
        let started = Instant::now();
        let messages = client
            .simple_query(sql)
            .map_err(|error| query_error(&error, sql))?;

        assemble(messages, types, started.elapsed())
    }

    pub fn catalog(&self) -> Result<Catalog, DbError> {
        let relations = self.internal_query(RELATIONS_SQL)?;
        let routines = self.internal_query(ROUTINES_SQL)?;
        assemble_catalog(relations, routines)
    }

    pub fn structure(&self, schema: &str, relation: &str) -> Result<Structure, DbError> {
        let columns =
            self.internal_query(&structure_sql(STRUCTURE_COLUMNS_SQL, schema, relation))?;
        let indexes =
            self.internal_query(&structure_sql(STRUCTURE_INDEXES_SQL, schema, relation))?;
        let constraints =
            self.internal_query(&structure_sql(STRUCTURE_CONSTRAINTS_SQL, schema, relation))?;
        assemble_structure(columns, indexes, constraints)
    }
}

/// The type of each column a statement would return, in order.
///
/// The simple query protocol hands back every value as text and describes none
/// of it, so the only way to know that a column of digits is an `int8` and not
/// a `numeric` is to ask separately. Preparing the statement asks: the server
/// parses and plans it and answers with the row description, and it never
/// executes anything — Postgres refuses to prepare the utility statements that
/// would have an effect, and refuses more than one statement at a time. Both
/// refusals arrive here as "no types known", which is the honest answer.
fn column_types(client: &mut Client, sql: &str) -> Vec<String> {
    client
        .prepare(sql)
        .map(|statement| {
            statement
                .columns()
                .iter()
                .map(|column| column.type_().name().to_string())
                .collect()
        })
        .unwrap_or_default()
}

fn structure_sql(template: &str, schema: &str, relation: &str) -> String {
    template
        .replace("{schema}", &quote_literal(schema))
        .replace("{relation}", &quote_literal(relation))
}

/// A relation name is user data and can contain a quote. Doubling is enough
/// because `standard_conforming_strings` is on by default, so a backslash in a
/// name is not an escape character.
fn quote_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn assemble(
    messages: Vec<SimpleQueryMessage>,
    types: Vec<String>,
    elapsed: Duration,
) -> Result<QueryResult, DbError> {
    let mut result = QueryResult {
        elapsed,
        ..Default::default()
    };
    // Matched by position, and only when the two agree on how many columns
    // there are: the description came from a separate round trip, and a type
    // put against the wrong column is worse than no type at all.
    let type_at = |index: usize, columns: usize| {
        (types.len() == columns)
            .then(|| types.get(index).cloned())
            .flatten()
    };

    for message in messages {
        match message {
            // One selection can carry several statements, and the grid shows
            // one result set -- so each new description starts the kept set
            // over and the last statement wins. Accumulating across statements
            // would put one statement's rows under another's column names.
            SimpleQueryMessage::RowDescription(columns) => {
                result.columns = columns
                    .iter()
                    .enumerate()
                    .map(|(index, column)| Column {
                        name: column.name().to_string(),
                        data_type: type_at(index, columns.len()),
                    })
                    .collect();
                result.rows.clear();
                result.bytes = 0;
                result.rows_affected = None;
            }
            SimpleQueryMessage::Row(row) => {
                // A row arriving with no description before it is not a path
                // the driver takes today; without this the grid would render
                // headerless and drop every value it was handed.
                if result.columns.is_empty() {
                    result.columns = row
                        .columns()
                        .iter()
                        .enumerate()
                        .map(|(index, column)| Column {
                            name: column.name().to_string(),
                            data_type: type_at(index, row.columns().len()),
                        })
                        .collect();
                }

                // `get` panics on a value the driver cannot decode as UTF-8,
                // and it would panic here holding the client mutex — poisoning
                // it and taking the process down with it. A database whose
                // encoding is SQL_ASCII can return such bytes for ordinary text.
                let cells: Vec<Cell> = (0..row.len())
                    .map(|index| {
                        row.try_get(index)
                            .map(|cell| cell.map(str::to_string))
                            .map_err(|_| non_utf8_error(&result.columns, index))
                    })
                    .collect::<Result<_, _>>()?;

                result.bytes += cells
                    .iter()
                    .filter_map(|cell| cell.as_ref().map(String::len))
                    .sum::<usize>();
                result.rows.push(cells);
            }
            SimpleQueryMessage::CommandComplete(count) => {
                result.rows_affected = Some(count);
            }
            _ => {}
        }
    }

    Ok(result)
}

fn assemble_catalog(relations: QueryResult, routines: QueryResult) -> Result<Catalog, DbError> {
    let mut schemas = std::collections::BTreeMap::<String, Schema>::new();

    for row in &relations.rows {
        let schema_name = required_cell(&relations, row, "schema_name")?;
        let name = required_cell(&relations, row, "relation_name")?;
        let kind = match required_cell(&relations, row, "relation_kind")? {
            "table" => RelationKind::Table,
            "partitioned_table" => RelationKind::PartitionedTable,
            "view" => RelationKind::View,
            "materialized_view" => RelationKind::MaterializedView,
            "foreign_table" => RelationKind::ForeignTable,
            kind => return Err(unexpected_catalog_value("relation kind", kind)),
        };

        schema(&mut schemas, schema_name).relations.push(Relation {
            name: name.to_string(),
            kind,
        });
    }

    for row in &routines.rows {
        let schema_name = required_cell(&routines, row, "schema_name")?;
        let name = required_cell(&routines, row, "routine_name")?;
        let kind = match required_cell(&routines, row, "routine_kind")? {
            "function" => RoutineKind::Function,
            "procedure" => RoutineKind::Procedure,
            kind => return Err(unexpected_catalog_value("routine kind", kind)),
        };

        schema(&mut schemas, schema_name).routines.push(Routine {
            name: name.to_string(),
            kind,
            identity_arguments: required_cell(&routines, row, "identity_arguments")?.to_string(),
            result_type: required_cell(&routines, row, "result_type")?.to_string(),
            language: required_cell(&routines, row, "language")?.to_string(),
            definition: required_cell(&routines, row, "definition")?.to_string(),
        });
    }

    Ok(Catalog {
        schemas: schemas.into_values().collect(),
    })
}

fn assemble_structure(
    columns: QueryResult,
    indexes: QueryResult,
    constraints: QueryResult,
) -> Result<Structure, DbError> {
    let mut structure = Structure::default();

    for row in &columns.rows {
        let default = required_cell(&columns, row, "column_default")?;
        structure.columns.push(ColumnDefinition {
            name: required_cell(&columns, row, "column_name")?.to_string(),
            data_type: required_cell(&columns, row, "data_type")?.to_string(),
            nullable: match required_cell(&columns, row, "nullable")? {
                "yes" => true,
                "no" => false,
                value => return Err(unexpected_catalog_value("nullability", value)),
            },
            default: (!default.is_empty()).then(|| default.to_string()),
        });
    }

    for (result, into) in [
        (&indexes, &mut structure.indexes),
        (&constraints, &mut structure.constraints),
    ] {
        for row in &result.rows {
            into.push(NamedDefinition {
                name: required_cell(result, row, "object_name")?.to_string(),
                definition: required_cell(result, row, "definition")?.to_string(),
            });
        }
    }

    Ok(structure)
}

fn schema<'a>(
    schemas: &'a mut std::collections::BTreeMap<String, Schema>,
    name: &str,
) -> &'a mut Schema {
    schemas.entry(name.to_string()).or_insert_with(|| Schema {
        name: name.to_string(),
        relations: Vec::new(),
        routines: Vec::new(),
    })
}

fn required_cell<'a>(
    result: &'a QueryResult,
    row: &'a [Cell],
    column_name: &str,
) -> Result<&'a str, DbError> {
    let index = result
        .columns
        .iter()
        .position(|column| column.name == column_name)
        .ok_or_else(|| catalog_error(format!("Catalog query omitted column {column_name}.")))?;

    row.get(index)
        .and_then(Option::as_deref)
        .ok_or_else(|| catalog_error(format!("Catalog query returned no {column_name}.")))
}

fn unexpected_catalog_value(label: &str, value: &str) -> DbError {
    catalog_error(format!("Catalog query returned unknown {label} {value}."))
}

fn non_utf8_error(columns: &[Column], index: usize) -> DbError {
    let column = columns
        .get(index)
        .map(|column| format!("column {}", column.name))
        .unwrap_or_else(|| format!("column {index}"));

    catalog_error(format!(
        "A value in {column} is not valid UTF-8 text and cannot be displayed."
    ))
}

fn catalog_error(message: String) -> DbError {
    DbError {
        message,
        position: None,
    }
}

fn connect_error(error: &postgres::Error, config: &ConnectionConfig) -> DbError {
    // A refused connection is the most common failure by a wide margin, and the
    // driver's own wording buries the endpoint. Say what happened, and nothing
    // about what the user should do -- we cannot see their machine.
    if let Some(io) = io_source(error)
        && io.kind() == std::io::ErrorKind::ConnectionRefused
    {
        return DbError {
            message: format!(
                "Connection refused: nothing is listening on {}",
                config.endpoint()
            ),
            position: None,
        };
    }

    DbError {
        message: describe(error),
        position: None,
    }
}

fn query_error(error: &postgres::Error, sql: &str) -> DbError {
    let position = error.as_db_error().and_then(|db| match db.position() {
        // Postgres reports a 1-based character position into the statement.
        Some(postgres::error::ErrorPosition::Original(p)) => {
            character_position_to_byte_offset(sql, *p)
        }
        _ => None,
    });

    DbError {
        message: describe(error),
        position,
    }
}

fn character_position_to_byte_offset(sql: &str, position: u32) -> Option<usize> {
    let character_index = position.checked_sub(1)? as usize;
    sql.char_indices()
        .map(|(byte_offset, _)| byte_offset)
        .chain(std::iter::once(sql.len()))
        .nth(character_index)
}

/// Prefer the server's own message. It is written for humans and already says
/// the useful part; the driver's wrapper text mostly repeats "db error".
fn describe(error: &postgres::Error) -> String {
    if let Some(db) = error.as_db_error() {
        let mut message = db.message().to_string();
        if let Some(detail) = db.detail() {
            message.push('\n');
            message.push_str(detail);
        }
        if let Some(hint) = db.hint() {
            message.push('\n');
            message.push_str(hint);
        }
        return message;
    }

    error.to_string()
}

fn io_source(error: &postgres::Error) -> Option<&std::io::Error> {
    let mut source = std::error::Error::source(error);
    while let Some(current) = source {
        if let Some(io) = current.downcast_ref::<std::io::Error>() {
            return Some(io);
        }
        source = current.source();
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> ConnectionConfig {
        ConnectionConfig {
            host: "db.example.test".into(),
            port: Some(8432),
            database: "slate_test".into(),
            user: "someone".into(),
            password: String::new(),
        }
    }

    /// The server the `live_` tests talk to, from the standard `PG*` variables.
    fn live_config() -> ConnectionConfig {
        ConnectionConfig {
            host: std::env::var("PGHOST").expect("PGHOST is required"),
            port: std::env::var("PGPORT")
                .ok()
                .map(|port| port.parse().expect("PGPORT must be a number")),
            database: std::env::var("PGDATABASE").expect("PGDATABASE is required"),
            user: std::env::var("PGUSER").expect("PGUSER is required"),
            password: std::env::var("PGPASSWORD").unwrap_or_default(),
        }
    }

    fn names(result: &QueryResult) -> Vec<&str> {
        result
            .columns
            .iter()
            .map(|column| column.name.as_str())
            .collect()
    }

    fn types(result: &QueryResult) -> Vec<Option<&str>> {
        result
            .columns
            .iter()
            .map(|column| column.data_type.as_deref())
            .collect()
    }

    #[test]
    fn connection_string_quotes_values() {
        let config = config();
        assert_eq!(
            config.connection_string(),
            "host='db.example.test' dbname='slate_test' user='someone' port=8432 connect_timeout=10"
        );
    }

    #[test]
    fn connection_string_omits_an_unspecified_port() {
        let config = ConnectionConfig {
            port: None,
            ..config()
        };
        assert!(!config.connection_string().contains("port="));
        assert_eq!(config.endpoint(), "db.example.test");
    }

    #[test]
    fn blank_password_is_omitted_not_sent_empty() {
        // An empty `password=''` is not the same as offering no password, and
        // IAM auth relies on the latter.
        let config = config();
        assert!(!config.connection_string().contains("password"));
    }

    #[test]
    fn username_with_at_sign_survives() {
        // Cloud IAM usernames are email addresses. A bare interpolation would
        // still work here, but quoting is what keeps it working.
        let config = ConnectionConfig {
            user: "person@example.com".into(),
            ..config()
        };
        assert!(
            config
                .connection_string()
                .contains("user='person@example.com'")
        );
    }

    #[test]
    fn quotes_and_backslashes_are_escaped() {
        let config = ConnectionConfig {
            password: r"pa'ss\word".into(),
            ..config()
        };
        assert!(
            config
                .connection_string()
                .contains(r"password='pa\'ss\\word'")
        );
    }

    #[test]
    fn spaces_in_values_do_not_split_the_string() {
        let config = ConnectionConfig {
            database: "my database".into(),
            ..config()
        };
        assert!(config.connection_string().contains("dbname='my database'"));
    }

    #[test]
    fn url_populates_fields_without_inventing_a_port() {
        let config = ConnectionConfig::from_url(
            "postgresql://person%40example.com@db.example.test/slate_test",
        )
        .unwrap();

        assert_eq!(
            config,
            ConnectionConfig {
                host: "db.example.test".into(),
                port: None,
                database: "slate_test".into(),
                user: "person@example.com".into(),
                password: String::new(),
            }
        );
    }

    #[test]
    fn url_preserves_an_explicit_port_and_password() {
        let config = ConnectionConfig::from_url(
            "postgres://someone:pa%20ss@db.example.test:8432/slate_test",
        )
        .unwrap();

        assert_eq!(config.port, Some(8432));
        assert_eq!(config.password, "pa ss");
    }

    #[test]
    fn server_character_positions_become_utf8_byte_offsets() {
        let sql = "SELECT 'é', broken";
        let broken_byte_offset = sql.find("broken").unwrap();
        let broken_character_position = sql[..broken_byte_offset].chars().count() as u32 + 1;
        assert_eq!(
            character_position_to_byte_offset(sql, broken_character_position),
            Some(broken_byte_offset)
        );
    }

    #[test]
    fn invalid_server_character_positions_are_rejected() {
        assert_eq!(character_position_to_byte_offset("SELECT 1", 0), None);
        assert_eq!(character_position_to_byte_offset("SELECT 1", 100), None);
    }

    fn result(columns: &[&str], rows: &[&[Option<&str>]]) -> QueryResult {
        QueryResult {
            columns: columns
                .iter()
                .map(|name| Column {
                    name: (*name).to_string(),
                    ..Default::default()
                })
                .collect(),
            rows: rows
                .iter()
                .map(|row| row.iter().map(|cell| cell.map(str::to_string)).collect())
                .collect(),
            ..Default::default()
        }
    }

    #[test]
    fn catalog_groups_relations_and_routines_by_schema() {
        let relations = result(
            &["schema_name", "relation_name", "relation_kind"],
            &[
                &[Some("analytics"), Some("events"), Some("partitioned_table")],
                &[Some("public"), Some("accounts"), Some("table")],
                &[Some("public"), Some("account_overview"), Some("view")],
            ],
        );
        let routines = result(
            &[
                "schema_name",
                "routine_name",
                "routine_kind",
                "identity_arguments",
                "result_type",
                "language",
                "definition",
            ],
            &[
                &[
                    Some("analytics"),
                    Some("refresh_events"),
                    Some("procedure"),
                    Some("full boolean"),
                    Some(""),
                    Some("plpgsql"),
                    Some("CREATE PROCEDURE analytics.refresh_events(full boolean)"),
                ],
                &[
                    Some("public"),
                    Some("account_name"),
                    Some("function"),
                    Some("account_id bigint"),
                    Some("text"),
                    Some("sql"),
                    Some("CREATE FUNCTION public.account_name(account_id bigint)"),
                ],
            ],
        );

        let catalog = assemble_catalog(relations, routines).unwrap();

        assert_eq!(catalog.schemas.len(), 2);
        assert_eq!(catalog.schemas[0].name, "analytics");
        assert_eq!(
            catalog.schemas[0].relations,
            vec![Relation {
                name: "events".into(),
                kind: RelationKind::PartitionedTable,
            }]
        );
        assert_eq!(catalog.schemas[0].routines[0].kind, RoutineKind::Procedure);
        assert_eq!(catalog.schemas[1].name, "public");
        assert_eq!(catalog.schemas[1].relations[1].kind, RelationKind::View);
        assert_eq!(catalog.schemas[1].routines[0].result_type, "text");
    }

    #[test]
    fn structure_reads_nullability_and_treats_a_blank_default_as_absent() {
        let columns = result(
            &["column_name", "data_type", "nullable", "column_default"],
            &[
                &[Some("id"), Some("bigint"), Some("no"), Some("nextval('s')")],
                &[Some("label"), Some("text"), Some("yes"), Some("")],
            ],
        );
        let indexes = result(
            &["object_name", "definition"],
            &[&[Some("accounts_pkey"), Some("CREATE UNIQUE INDEX …")]],
        );
        let constraints = result(
            &["object_name", "definition"],
            &[&[Some("accounts_pkey"), Some("PRIMARY KEY (id)")]],
        );

        let structure = assemble_structure(columns, indexes, constraints).unwrap();

        assert_eq!(
            structure.columns,
            vec![
                ColumnDefinition {
                    name: "id".into(),
                    data_type: "bigint".into(),
                    nullable: false,
                    default: Some("nextval('s')".into()),
                },
                ColumnDefinition {
                    name: "label".into(),
                    data_type: "text".into(),
                    nullable: true,
                    default: None,
                },
            ]
        );
        assert_eq!(structure.indexes[0].name, "accounts_pkey");
        assert_eq!(structure.constraints[0].definition, "PRIMARY KEY (id)");
    }

    #[test]
    fn structure_sql_quotes_a_name_containing_a_quote() {
        let sql = structure_sql(
            "WHERE namespace.nspname = {schema} AND class.relname = {relation}",
            "public",
            "odd'name",
        );

        assert_eq!(
            sql,
            "WHERE namespace.nspname = 'public' AND class.relname = 'odd''name'"
        );
    }

    #[test]
    fn a_url_demanding_tls_is_refused_rather_than_sent_in_the_clear() {
        let error = ConnectionConfig::from_url(
            "postgresql://someone@db.example.test/slate_test?sslmode=require",
        )
        .unwrap_err();

        assert!(error.contains("TLS"), "unexpected message: {error}");
    }

    #[test]
    fn a_url_without_tls_still_parses() {
        for mode in ["disable", "prefer"] {
            let url = format!("postgresql://someone@db.example.test/slate_test?sslmode={mode}");
            assert!(
                ConnectionConfig::from_url(&url).is_ok(),
                "sslmode={mode} should be accepted"
            );
        }
    }

    #[test]
    fn catalog_rejects_unknown_object_kinds() {
        let relations = result(
            &["schema_name", "relation_name", "relation_kind"],
            &[&[Some("public"), Some("mystery"), Some("unknown")]],
        );

        let error = assemble_catalog(relations, QueryResult::default()).unwrap_err();

        assert_eq!(
            error.message,
            "Catalog query returned unknown relation kind unknown."
        );
    }

    #[test]
    #[ignore = "requires a local Postgres server configured through PG*"]
    fn live_query_round_trip() {
        let connection = Connection::open(live_config()).expect("connection should open");
        let result = connection
            .query("SELECT * FROM (VALUES (1, 'alpha'), (2, NULL)) AS sample(id, label)")
            .expect("query should succeed");

        assert_eq!(names(&result), vec!["id", "label"]);
        // Types come from describing the statement, which the simple protocol
        // itself cannot answer for. `text` for the second column is the
        // server's own answer for an unadorned literal.
        assert_eq!(types(&result), vec![Some("int4"), Some("text")]);
        assert_eq!(
            result.rows,
            vec![
                vec![Some("1".into()), Some("alpha".into())],
                vec![Some("2".into()), None]
            ]
        );
        assert_eq!(result.bytes, 7);
        assert_eq!(result.rows_affected, Some(2));
    }

    #[test]
    #[ignore = "requires a local Postgres server configured through PG*"]
    fn live_a_multi_statement_selection_keeps_one_result_shape() {
        // `assemble` cannot be unit-tested -- SimpleQueryRow and SimpleColumn
        // have no public constructor -- so the ragged-rows panic is guarded
        // here. Before the RowDescription arm existed this produced 3 columns
        // against a 1-cell row, and the grid aborted the process painting it.
        let connection = Connection::open(live_config()).expect("connection should open");

        let result = connection
            .query("SELECT 1 AS a, 2 AS b, 3 AS c; SELECT 4 AS d")
            .expect("query should succeed");

        assert_eq!(names(&result), vec!["d"]);
        assert_eq!(result.rows, vec![vec![Some("4".into())]]);
        assert!(
            result.rows.iter().all(|row| row.len() == result.columns.len()),
            "every row must match the column count"
        );

        // A valid empty result still has to carry its headers.
        let empty = connection
            .query("SELECT 1 AS id, 'x' AS label WHERE false")
            .expect("query should succeed");

        assert_eq!(names(&empty), vec!["id", "label"]);
        assert!(empty.rows.is_empty());
    }

    #[test]
    #[ignore = "requires the repository development database configured through PG*"]
    fn live_structure_round_trip() {
        let structure = Connection::open(live_config())
            .expect("connection should open")
            .structure("public", "accounts")
            .expect("structure should load");

        let id = structure
            .columns
            .iter()
            .find(|column| column.name == "id")
            .expect("accounts.id should exist");
        assert!(!id.nullable);
        assert_eq!(
            id.default.as_deref(),
            Some("GENERATED ALWAYS AS IDENTITY"),
            "an identity column has no pg_attrdef row to read"
        );
        assert!(
            structure
                .columns
                .iter()
                .any(|column| column.name == "email" && column.nullable)
        );
        assert!(
            structure
                .columns
                .iter()
                .any(|column| column.name == "email" && column.data_type == "text")
        );
        assert!(
            structure
                .constraints
                .iter()
                .any(|constraint| constraint.definition.starts_with("PRIMARY KEY"))
        );
        assert!(!structure.indexes.is_empty(), "the primary key is an index");
    }

    #[test]
    #[ignore = "requires the repository development database configured through PG*"]
    fn live_catalog_round_trip() {
        let catalog = Connection::open(live_config())
            .expect("connection should open")
            .catalog()
            .expect("catalog should load");
        let public = catalog
            .schemas
            .iter()
            .find(|schema| schema.name == "public")
            .expect("public schema should exist");

        assert!(
            public
                .relations
                .iter()
                .any(|relation| relation.name == "accounts" && relation.kind == RelationKind::Table)
        );
        assert!(public.relations.iter().any(|relation| {
            relation.name == "account_overview" && relation.kind == RelationKind::View
        }));

        assert!(
            public
                .routines
                .iter()
                .any(|routine| routine.name == "account_label"
                    && routine.kind == RoutineKind::Function),
            "the database's own routines must be listed"
        );
        // PostGIS installs ~750 routines into `public`. None of them belong in
        // a sidebar listing what the user wrote.
        assert!(
            !public
                .routines
                .iter()
                .any(|routine| routine.name.starts_with("st_")
                    || routine.name.starts_with("_postgis")),
            "extension-owned routines must not be listed"
        );
    }
}
